name: jenkins
summary: Jenkins automation server
base: core20
description: |
  Jenkins is the leading open-source automation server. Built with Java, it
  provides over 1000 plugins to support automating virtually anything, so that
  humans can actually spend their time doing things machines cannot.

adopt-info: jenkins

confinement: classic
grade: stable

apps:
  jenkins:
    environment:
      XDG_DATA_HOME: "$SNAP/usr/share"
      FONTCONFIG_PATH: "$SNAP/etc/fonts"
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-17-openjdk"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
    command: launch            
    daemon: simple
  config:
    command: jenkins-config

parts:
    jenkins:
        plugin: nil
        source: https://github.com/jenkinsci/jenkins.git # in lieu of the BGI trigger which didn't seem to work
        stage-packages:
            - fonts-dejavu-core
            - libfontconfig1
            - openjdk-17-jre-headless
            - ca-certificates-java
        build-packages:
            - curl
            - libnss3
            - ca-certificates-java
        
        override-pull: |
          snapcraftctl pull
          snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f2)"
        
        override-build: |
            curl -sLO http://mirrors.jenkins.io/war/latest/jenkins.war
            mv $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-17-openjdk-* $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-17-openjdk
            rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-17-openjdk/lib/security/cacerts
            cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-17-openjdk/lib/security/cacerts
            cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts
            mv jenkins.war $SNAPCRAFT_PART_INSTALL
                       
    config:
        plugin: dump
        source: snap/local
        prime:
            - jenkins-config
            - launch
            - -usr/lib/jvm/java-17-openjdk-amd64/lib/security/blacklisted.certs
            - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
    cleanup:
      after: 
        - jenkins
      plugin: nil
      build-snaps: 
        - core20
      override-prime: |
        set -eux
        for snap in "core20"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
        done
